const express = require('express')
const router = express.Router()
const { verifyToken } = require('../middlewares/auth.js')

router.use('/auth', require('./auth'))
router.use('/auth/customer', require('./customer-auth'))

router.use('/admin/users', verifyToken, require('./admin/users'))
router.use('/admin/customers', verifyToken, require('./admin/customers'))
router.use('/admin/bots', verifyToken, require('./admin/bots'))
router.use('/admin/customer-bot-chats', verifyToken, require('./admin/customer-bot-chats'))
router.use('/admin/customer-bots', verifyToken, require('./admin/customer-bots'))
router.use('/admin/customer-events', verifyToken, require('./admin/customer-events'))
router.use('/admin/events', verifyToken, require('./admin/events'))
router.use('/admin/event-categories', verifyToken, require('./admin/event-categories'))
router.use('/admin/event-occurrences', verifyToken, require('./admin/event-occurrences'))
router.use('/admin/event-prices', verifyToken, require('./admin/event-prices'))
router.use('/admin/faqs', verifyToken, require('./admin/faqs'))
router.use('/admin/heroes', verifyToken, require('./admin/heroes'))
router.use('/admin/languages', verifyToken, require('./admin/languages'))
router.use('/admin/promoters', verifyToken, require('./admin/promoters'))
router.use('/admin/promoter-spots', verifyToken, require('./admin/promoter-spots'))
router.use('/admin/towns', verifyToken, require('./admin/towns'))

router.use('/customer/faqs', require('./customer/faqs'))
router.use('/customer/heroes', require('./customer/heroes'))
router.use('/customer/chats', require('./customer/chats'))
router.use('/customer/search', require('./customer/search'))

module.exports = router
